# Generated by Django 5.1 on 2024-09-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillOfMaterial',
            new_name='BillOfMaterials',
        ),
    ]
