# Generated by Django 5.1 on 2024-09-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0002_rename_billofmaterial_billofmaterials"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterial",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="billofmaterials",
            name="final_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bom",
                to="bom.product",
            ),
        ),
    ]
