# Generated by Django 5.1 on 2024-09-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0003_rawmaterial_slug_alter_billofmaterials_final_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
