# Generated by Django 5.1 on 2024-09-03 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0007_alter_rawmaterial_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawmaterial",
            name="slug",
        ),
    ]
