# Generated by Django 5.1 on 2024-09-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0008_remove_rawmaterial_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterial",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
