# Generated by Django 5.1 on 2024-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom", "0010_alter_rawmaterial_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
