# Generated by Django 5.0.7 on 2024-09-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0011_alter_rawmaterial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='semi_finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='bom.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='bom.rawmaterial'),
        ),
    ]
