# Generated by Django 5.0.7 on 2024-09-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0012_billofmaterials_semi_finished_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
